apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: https-stack
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/marianorapa/sd-2026
    targetRevision: HEAD
    path: https-en-k8s/k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
