server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    # Servir el frontend
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Proxy hacia los microservicios internos (Kubernetes DNS)
    location /api/users {
        proxy_pass http://users-api-service/users;
        proxy_set_header Host $host;
    }

    location /api/products {
        proxy_pass http://products-api-service/products;
        proxy_set_header Host $host;
    }

    # Health check para GKE
    location /health {
        return 200 'ok';
        add_header Content-Type text/plain;
    }
}
